# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47db9a19063f1d3ac99d4d1dc78c63a2bd0f28b64a424897f9f86d2c5b19dc799abe0dcb6b9c1d3671b35222539d057f2498f327f3a7758c11e9dba561deb090

test:
  secret_key_base: efd9c3059f74d6edd46bb34b43e9efda9de7e98796284f34be9412022568fc972dd849985a13962dfbbb095dfb9731a74ef693dbe0e953100074d3ad238ff9b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
